### ISSUE TITLE
Feature request : iOS spelling checker 

### ISSUE THREAD

**Issue by mrtpcet** [dec0dOS/standard-notes-fast-editor#1]
Hello and thanks for your great editor !
The only thing that annoy me is the absence of the iOS spelling checker. 
it’s possible for you to include that ?

Thanks !

**Comment by dec0dOS** [comment]
Hello! This editor is a fork of [MaxLap's Indent Editor](https://github.com/MaxLap/standard-notes-indent-editor/) and shares the [same CodeMirror issue](https://github.com/MaxLap/standard-notes-indent-editor/issues/19). 

For now, this feature is really hard to implement, sorry.

**Comment by mrtpcet** [comment]
Ok ! I understand. 
if it can help, this one does : https://github.com/arturolinares/sn-rme

**Comment by dec0dOS** [comment]
Hey! Check out my new [Ultimate Editor](https://github.com/dec0dOS/standard-notes-ultimate-editor). It is quite stable for now and fixes many Fast Editor's issues. Due to CodeMirror 6 under the hood and the full rewrite, this issue has gone.
