### ISSUE TITLE
Bold and italic text

### ISSUE THREAD

**Issue by m3dragos** [dec0dOS/standard-notes-fast-editor#3]
It seems like currently it isn't possible to mark text as bold or italic.
Any ideas of workarounds for this?

**Comment by dec0dOS** [comment]
Hello! There were several issues with marking text as bold or italic before. If you are interested in this feature, feel free to submit the PR.
Currently, I'm developing the [Standard Notes Ultimate Editor](https://github.com/dec0dOS/standard-notes-ultimate-editor), It may even be better for your needs (it supports marking text as bold and italic)
